name: fuzzing-decision
tests:
  - name: python 3.6 unittests
    type: tox
    image: ci-py-36
    toxenv: py3
  - name: python 3.7 unittests
    type: tox
    image: ci-py-37
    toxenv: py3
  - name: python 3.8 unittests
    type: tox
    image: ci-py-38
    toxenv: py3
  - name: python 3.9 unittests
    type: tox
    image: ci-py-39
    toxenv: py3
  - name: python 3.10 unittests
    type: tox
    image: ci-py-310
    toxenv: py3
  - name: python 3.11 unittests
    type: tox
    image: ci-py-311
    toxenv: py3
  - name: lint
    type: tox
    image: ci-py-38
    toxenv: lint
